// ký tự mũi tên cho các trường hợp dạng chữ: ▸
// Dùng cái này để fix lỗi gõ tiếng Việt Unikey 4.3 RC5: ·
// whitespace entity: &nbsp;

export const requestApiTimeout = 60000;
export const sourceVersion = 1;

export const layoutSizes = 1274; // 1242 + 32
export const navbarSizes = {
    desktop: 108,
    mobile: 66,
};

export const provinceOptions = [
    { value: 1, label: 'An Giang' },
    { value: 2, label: 'Bà Rịa - Vũng Tàu', },
    { value: 3, label: 'Bạc Liêu', },
    { value: 4, label: 'Bắc Kạn', },
    { value: 5, label: 'Bắc Giang', },
    { value: 6, label: 'Bắc Ninh', },
    { value: 7, label: 'Bến Tre', },
    { value: 8, label: 'Bình Dương', },
    { value: 9, label: 'Bình Định', },
    { value: 10, label: 'Bình Phước', },
    { value: 11, label: 'Bình Thuận', },
    { value: 12, label: 'Cà Mau', },
    { value: 13, label: 'Cao Bằng', },
    { value: 14, label: 'Cần Thơ', },
    { value: 15, label: 'Đà Nẵng', },
    { value: 16, label: 'Đắk Lắk', },
    { value: 17, label: 'Đắk Nông', },
    { value: 18, label: 'Điện Biên', },
    { value: 19, label: 'Đồng Nai', },
    { value: 20, label: 'Đồng Tháp', },
    { value: 21, label: 'Gia Lai', },
    { value: 22, label: 'Hà Giang', },
    { value: 23, label: 'Hà Nam', },
    { value: 24, label: 'Hà Nội', },
    { value: 25, label: 'Hà Tây', },
    { value: 26, label: 'Hà Tĩnh', },
    { value: 27, label: 'Hải Dương', },
    { value: 28, label: 'Hải Phòng', },
    { value: 29, label: 'Hòa Bình', },
    { value: 30, label: 'Hồ Chí Minh', },
    { value: 31, label: 'Hậu Giang', },
    { value: 32, label: 'Hưng Yên', },
    { value: 33, label: 'Khánh Hòa', },
    { value: 34, label: 'Kiên Giang', },
    { value: 35, label: 'Kon Tum', },
    { value: 36, label: 'Lai Châu', },
    { value: 37, label: 'Lào Cai', },
    { value: 38, label: 'Lạng Sơn', },
    { value: 39, label: 'Lâm Đồng', },
    { value: 40, label: 'Long An', },
    { value: 41, label: 'Nam Định', },
    { value: 42, label: 'Nghệ An', },
    { value: 43, label: 'Ninh Bình', },
    { value: 44, label: 'Ninh Thuận', },
    { value: 45, label: 'Phú Thọ', },
    { value: 46, label: 'Phú Yên', },
    { value: 47, label: 'Quảng Bình', },
    { value: 48, label: 'Quảng Nam', },
    { value: 49, label: 'Quảng Ngãi', },
    { value: 50, label: 'Quảng Ninh', },
    { value: 51, label: 'Quảng Trị', },
    { value: 52, label: 'Sóc Trăng', },
    { value: 53, label: 'Sơn La', },
    { value: 54, label: 'Tây Ninh', },
    { value: 55, label: 'Thái Bình', },
    { value: 56, label: 'Thái Nguyên', },
    { value: 57, label: 'Thanh Hóa', },
    { value: 58, label: 'Thừa Thiên - Huế', },
    { value: 59, label: 'Tiền Giang', },
    { value: 60, label: 'Trà Vinh', },
    { value: 61, label: 'Tuyên Quang', },
    { value: 62, label: 'Vĩnh Long', },
    { value: 63, label: 'Vĩnh Phúc', },
    { value: 64, label: 'Yên Bái', },
];